---
- name: Install the openconnect packag
  include_task: install_openconnect.yml

- name: Install the openconnect packag
  include_task: default_folders.yml

- name: GlobalProtect Startup Script
  include_task: openconnect_global_protect_startup.yml
